"""Weekly platform health report generator."""

from __future__ import annotations

import os
from datetime import datetime, timezone
from conductor.core.models import PlatformHealth, RepoHealth
from conductor.core.config import ConductorConfig


def compute_platform_health(repo_health: list[RepoHealth], config: ConductorConfig) -> PlatformHealth:
    """Aggregate repo health into platform-wide health."""
    healthy = [r for r in repo_health if r.status == "healthy"]
    failed = [r for r in repo_health if r.status == "failed"]
    degraded = [r for r in repo_health if r.status == "degraded"]

    platform_score = int(sum(r.health_score for r in repo_health) / max(len(repo_health), 1))

    return PlatformHealth(
        checked_at=datetime.now(timezone.utc).isoformat(),
        total_repos=len(repo_health),
        healthy_repos=len(healthy),
        failed_repos=len(failed) + len(degraded),
        skipped_repos=0,
        platform_score=platform_score,
        repo_health=repo_health,
        failures=[r.repo for r in failed + degraded],
    )


def generate_weekly_narrative(health: PlatformHealth, config: ConductorConfig) -> str:
    """Generate weekly platform narrative."""
    if config.has_api_key:
        return _ai_narrative(health, config)
    return _template_narrative(health)


def _ai_narrative(health: PlatformHealth, config: ConductorConfig) -> str:
    try:
        from openai import OpenAI
        client = OpenAI(base_url="https://openrouter.ai/api/v1", api_key=config.openrouter_api_key)
        prompt = f"""You are a platform engineering lead writing a weekly state-of-the-platform summary for a {config.industry} engineering organization.

Platform health this week:
- Overall score: {health.platform_score}/100
- Repos monitored: {health.total_repos}
- Healthy: {health.healthy_repos} ({health.health_pct}%)
- Failed/degraded: {health.failed_repos}
- Failures: {', '.join(health.failures) or 'none'}

Write a concise 3-paragraph weekly summary:
1. Overall platform health and trend
2. Any failures or issues requiring attention
3. What this means for delivery and compliance in {config.industry}

Be direct and data-driven. Write for an engineering audience."""

        message = client.chat.completions.create(
            model="meta-llama/llama-3.1-8b-instruct:free",
            max_tokens=500,
            messages=[{"role": "user", "content": prompt}],
        )
        return message.choices[0].message.content
    except Exception:
        return _template_narrative(health)


def _template_narrative(health: PlatformHealth, config: "ConductorConfig | None" = None) -> str:
    status = "healthy" if health.platform_score >= 80 else "degraded" if health.platform_score >= 60 else "at risk"
    return f"""## Weekly Platform Health Summary

Platform is **{status}** this week with an overall score of {health.platform_score}/100.
{health.healthy_repos} of {health.total_repos} repos ({health.health_pct}%) are operating normally.

{"No failures detected this week. All nightly agents ran successfully." if not health.failures else f"Failures detected in: {', '.join(health.failures)}. Automated issues have been opened in the affected repos."}

All changes are tracked per fintech compliance requirements.
Nightly agent runs provide continuous evidence of platform operation.
"""


def format_discussion_post(health: PlatformHealth, narrative: str) -> str:
    """Format the weekly report as a GitHub Discussions post."""
    date = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    status_emoji = "âœ…" if health.platform_score >= 80 else "âš ï¸" if health.platform_score >= 60 else "ðŸ”´"
    rows = "\n".join(
        f"| `{r.repo}` | {r.health_score}/100 | {'âœ…' if r.agent_succeeded else 'âŒ'} | {'âœ…' if r.ci_succeeded else 'âŒ'} |"
        for r in sorted(health.repo_health, key=lambda x: x.health_score, reverse=True)
    )
    return f"""# {status_emoji} Weekly Platform Health â€” {date}

**Platform score**: {health.platform_score}/100 | **Repos healthy**: {health.healthy_repos}/{health.total_repos} ({health.health_pct}%)

---

{narrative}

---

## Repo health matrix

| Repo | Score | Agent | CI |
|------|-------|-------|----|
{rows}

---

*Generated by [platform-conductor](https://github.com/brianpelow/platform-conductor) Â· {date}*
"""
